version: "3.8"
services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: rxocy
      POSTGRES_PASSWORD: rxocy
      POSTGRES_DB: rxocy
    restart: always
    networks:
      - project
networks:
  project: